---
version: '3'

# silent: true

vars:
  CC: /opt/homebrew/opt/llvm/bin/clang -I/usr/local/include # normal apple clang was having issues with address sanitizer for me
  CC_FLAGS: "-O0 -Werror -Wextra -Wall -Wfree-nonheap-object -std=c17"
  EXECUTABLE_NAME: main
  SOURCE_FILES:
    - main.c

tasks:
  default:
    silent: true
    cmds:
      - task: build
      - task: build:sanitize
      - task: build:debug
      - task: build:with-dylib

  build:
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        -o {{.EXECUTABLE_NAME}}
    sources:
      - ./main.c
    generates:
      - "{{.EXECUTABLE_NAME}}"

  run:
    deps:
      - build
    cmds:
      - ./{{.EXECUTABLE_NAME}}

  build:sanitize:
    run: once
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        -fsanitize=address \
        -fno-omit-frame-pointer \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        -o {{.EXECUTABLE_NAME}}-sanitize
    sources:
      - ./main.c
    generates:
      - "{{.EXECUTABLE_NAME}}-sanitize"

  run:sanitize:
    deps:
      - build:sanitize
    cmds:
      - ./{{.EXECUTABLE_NAME}}-sanitize

  build:debug:
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        -g \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        -o {{.EXECUTABLE_NAME}}-debug
    sources:
      - ./main.c
    generates:
      - "{{.EXECUTABLE_NAME}}-debug"

  clean:
    allow_failures: true
    cmds:
      - rm -f {{.EXECUTABLE_NAME}}
      - rm -f {{.EXECUTABLE_NAME}}-debug
      - rm -f {{.EXECUTABLE_NAME}}-sanitize
      - rm -f {{.EXECUTABLE_NAME}}-optimize
      - rm -f {{.EXECUTABLE_NAME}}-with-lib
      - rm -f a.out
      - rm -rf {{.EXECUTABLE_NAME}}-debug.dSYM
      - rm -f *.dylib
      # - task clean --taskfile ./lib/Taskfile.yml

  build:with-dylib:
    cmds:
      - task --taskfile ./lib/Taskfile.yml
      - |
        {{.CC}} {{.CC_FLAGS}} \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        {{.DYN_LIBS_USED_PATH}} \
        {{.DYN_LIBS_USED}} \
        -o {{.EXECUTABLE_NAME}}-with-lib
    vars:
      DYN_LIBS_USED_PATH: "-L/usr/local/lib/standardloop"
      DYN_LIBS_USED: "-lstandardloop-medium"
      SOURCE_FILES:
        - main-with-lib.c
    sources:
      - ./main-with-lib.c
    generates:
      - "{{.EXECUTABLE_NAME}}-with-lib"

  leaks:with-dylib:
    cmds:
      - task: leaks:with-dylib:run

  leaks:with-dylib:cp:
    deps:
      - build:with-dylib
    cmds:
      - cp /usr/local/lib/standardloop/libstandardloop-medium.dylib ./

  leaks:with-dylib:clean:
    cmds:
      - rm -f libstandardloop-medium.dylib

  leaks:with-dylib:run:
    deps:
      - leaks:with-dylib:cp
    cmds:
      - leaks --atExit -- ./{{.EXECUTABLE_NAME}}-with-lib
      - task: leaks:clean

  build:scribble:
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        scribble.c \
        {{.DYN_LIBS_USED_PATH}} \
        {{.DYN_LIBS_USED}} \
        -o scribble
    sources:
      - ./*.c
    generates:
      - scribble


  run:scribble:
    cmds:
      - export MallocScribble=1
      - export MallocPreScribble=1
      - ./scribble
