---
version: '3'

vars:
  DEPENDENCIES:
    - rdctl
    - docker

check-docker-running: &check-docker-running |
  docker info > /dev/null 2>&1

tasks:
  default:
    aliases: [all, make]
    deps:
      - check-dependencies
      - run-rancher

  check-dependencies:
    run: once
    silent: true
    cmds:
      - |
        {{range .DEPENDENCIES}}
          if ! command -v {{.}} > /dev/null; then
            echo "{{.}} not found"
          fi
        {{end}}

  run-rancher:
    run: once
    cmds:
      - rdctl start
      - |
        until docker info > /dev/null 2>&1
        do
          echo "waiting for docker to come up...."
          sleep 5
        done
        echo "docker is ready!"
    status:
      - rdctl list-settings > /dev/null 2>&1
      - *check-docker-running

  clean-rancher:
    cmds:
      - rdctl shutdown

  clean:
    aliases: [delete]
    ignore_error: true
    cmds:
      - task: clean-rancher
