#ifndef STANDARDLOOP_MEDIUM_H
#define STANDARDLOOP_MEDIUM_H

#define STANDARDLOOP_MEDIUM_H_MAJOR_VERSION 0
#define STANDARDLOOP_MEDIUM_H_MINOR_VERSION 0
#define STANDARDLOOP_MEDIUM_H_PATCH_VERSION 1
#define STANDARDLOOP_MEDIUM_H_VERSION "0.0.1"

extern void GenerateLeak();

#endif
