---
version: '3'

vars:
  INGRESS_NGINX_NS: "ingress-nginx"
  INGRESS_NGINX_VERSION: 4.13.3
  CLUSTER_NAME: slke-1
  DEPENDENCIES:
    - docker
    - kind
    - helm
    - cloud-provider-kind
    - kubectl

check-docker-running: &check-docker-running |
  docker info > /dev/null 2>&1

check-cluster-running: &check-cluster-running |
  kind get clusters | grep {{.CLUSTER_NAME}}

check-cloud-provider-kind-running: &check-cloud-provider-kind-running |
  pgrep sudo cloud-provider-kind

tasks:
  default:
    aliases: [all, make]
    deps:
      - check-dependencies
      - create-cluster
      - run-cloud-provider-kind
      - deploy-ingress
      - deploy-app
      - update-etc-hosts
      - open-app

  check-dependencies:
    silent: true
    cmds:
      - |
        {{range .DEPENDENCIES}}
          if ! command -v {{.}} > /dev/null; then
            echo "{{.}} not found"
          fi
        {{end}}
        if ! helm plugin list | grep -q diff > /dev/null; then
            echo "helm diff plugin is missing"
        fi

  create-cluster:
    run: once
    preconditions:
      - *check-docker-running
    cmds:
      - kind create cluster --config=./kind-config.yaml
    status:
      - *check-cluster-running

  run-cloud-provider-kind:
    run: once
    deps:
      - create-cluster
    interactive: true
    cmds:
      - sudo -v
      - bash -c 'nohup sudo cloud-provider-kind >/dev/null 2>&1 &'
    status:
      - *check-cloud-provider-kind-running

  deploy-ingress:
    run: once
    deps:
      - run-cloud-provider-kind
    cmds:
      - |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --create-namespace \
          -n {{.INGRESS_NGINX_NS}} \
          --values ingress-nginx.values.yaml \
          --version {{.INGRESS_NGINX_VERSION}} \
          --wait
    status:
      - |
        helm diff upgrade ingress-nginx ingress-nginx/ingress-nginx \
          -n {{.INGRESS_NGINX_NS}} \
          --values ingress-nginx.values.yaml \
          --version {{.INGRESS_NGINX_VERSION}} \

  clean-ingress:
    cmds:
      - helm uninstall ingress-nginx -n {{.INGRESS_NGINX_NS}}

  deploy-app:
    run: once
    deps:
      - deploy-ingress
    cmds:
      - kubectl apply -f app.yaml
    status:
      - kubectl diff -f app.yaml

  clean-app:
    cmds:
      - kubectl delete -f app.yaml

  update-etc-hosts:
    run: once
    prompt: Do you want to update /etc/hosts ?
    deps:
      - deploy-app
    cmds:
      - echo {{.LOAD_BALANCER_IP}}
      - sudo -v
      - echo "{{.LOAD_BALANCER_IP}}      kind.local" | sudo tee -a /etc/hosts
    status:
      - cat /etc/hosts | grep {{.LOAD_BALANCER_IP}}
    vars:
      LOAD_BALANCER_IP:
        sh: kubectl get svc/ingress-nginx-controller -n {{.INGRESS_NGINX_NS}} -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'  # yamllint disable-line rule:line-length

  open-app:
    deps:
      - deploy-app
    cmds:
      - open http://kind.local

  clean-cloud-provider-kind:
    interactive: true
    cmds:
      - *check-cloud-provider-kind-running
      - sudo -v
      - sudo pkill cloud-provider-kind

  clean-cluster:
    cmds:
      - kind delete cluster --name {{.CLUSTER_NAME}}

  clean:
    aliases: [delete]
    ignore_error: true
    cmds:
      - task: clean-app
      - task: clean-ingress
      - task: clean-cluster
      - task: clean-cloud-provider-kind
      - echo "make sure to reset your etc/hosts!"
