#ifndef STANDARDLOOP_ADD_H
#define STANDARDLOOP_ADD_H

#define STANDARDLOOP_ADD_H_MAJOR_VERSION 0
#define STANDARDLOOP_ADD_H_MINOR_VERSION 0
#define STANDARDLOOP_ADD_H_PATCH_VERSION 1
#define STANDARDLOOP_ADD_H_VERSION "0.0.1"

int add(int, int);

#endif
